Update patch set 2
Patch Set 2:

This can not pass until the core promote job passes:

Error: Invalid parameter force_power_state_during_sync on Class[Ironic::Conductor] at /etc/puppet/manifests/puppet-stack-config.pp:326 on node instack

We will need to make the core promote job use the RPM from PS2 as a workaround to get it to pass.

Patch-set: 2