Update patch set 3
Patch Set 3: Code-Review-1

This causes re-running `openstack undercloud install` to fail with:

+ openstack role add --user admin --project service swiftoperator
ERROR: openstack Conflict occurred attempting to store role grant - User c1915e25238f4c6ca1a6c1f7eea960a8 already has role 6306d69363c540459778f

I need to add a check for the role already existing. It might be good to include re-running the undercloud install on the gate too.

Patch-set: 3
Reviewer: John Trowbridge <1003529@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Code-Review=-1