Add ntp element to overcloud-full images
The RDO promote job is failing to deploy because at some
point we started expecting for ntpd to be installed in the
overcloud images.

Error: Could not start Service[ntp]: Execution of
'/usr/bin/systemctl start ntpd' returned 6: Failed to issue
method call: Unit ntpd.service failed to load: No such file
or directory.
Wrapped exception:
Execution of '/usr/bin/systemctl start ntpd' returned 6:
Failed to issue method call: Unit ntpd.service failed to
load: No such file or directory.

Change-Id: Iabff3bd5c9deea3f5663adc4b1ec6768a21a9002