Update patch set 1
Patch Set 1:

WRT the changes in the quiesce_compute, failed for me using just the ID:

[stack@instack ~]$ nova service-list
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+
| Id | Binary           | Host                               | Zone     | Status  | State | Updated_at                 | Disabled Reason |
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+
| 1  | nova-scheduler   | overcloud-controller-0.localdomain | internal | enabled | up    | 2015-08-04T11:56:08.000000 | -               |
| 2  | nova-consoleauth | overcloud-controller-0.localdomain | internal | enabled | up    | 2015-08-04T11:56:01.000000 | -               |
| 3  | nova-conductor   | overcloud-controller-0.localdomain | internal | enabled | up    | 2015-08-04T11:56:03.000000 | -               |
| 4  | nova-compute     | overcloud-compute-0.localdomain    | nova     | enabled | up    | 2015-08-04T11:56:05.000000 | -               |
| 5  | nova-compute     | overcloud-compute-1.localdomain    | nova     | enabled | up    | 2015-08-04T11:56:04.000000 | -               |
+----+------------------+------------------------------------+----------+---------+-------+----------------------------+-----------------+

[stack@instack ~]$ nova service-disable 5
usage: nova service-disable [--reason <reason>] <hostname> <binary>
error: too few arguments
Try 'nova help service-disable' for more information.
[stack@instack ~]$ nova service-disable 5 nova-compute
ERROR (NotFound): Could not find binary nova-compute on host 5. (HTTP 404) (Request-ID: req-3ce8eb00-7bbe-4ed4-b119-f5ad168fe3a6)

Patch-set: 1