Update patch set 1
Patch Set 1: Code-Review-1 Verified-1

error: file '/home/fedora/rpmbuild/BUILD/instack-undercloud-2.0.0.dev1424.gb263717/scripts/instack-delete-overcloud' does not exist

Probably needs to be removed from setup.cfg too.

Patch-set: 1
Label: Code-Review=-1
Label: Verified=-1